<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Selection\Api\Representation\SelectionItemRepresentation|null $selectionItem
 * @var string $url
 * @var string $action deprecated "add" or "delete". Check selection item instead.
 * @var string $text
 * and options passed from the caller.
 */

?>

<i class="fas fa-shopping-selection"></i> <?= $text ?>
