<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var string $action
 * @var string $url
 */

$translate = $this->plugin('translate');

$text = $action === 'add' ? $translate('Add to basket') : $translate('Remove from basket');
$class = "basket-$action";
?>

<button class="basket-update <?= $class ?>" title="<?= $text ?>" data-url="<?= $url ?>">
    <?= $this->partial('common/basket-button-content', ['action' => $action, 'text' => $text]) ?>
</button>
