<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Basket\Api\Representation\BasketItemRepresentation|null $basketItem
 * @var string $url
 * @var string $action deprecated "add" or "delete". Check basket item instead.
 * @var string $text
 * and options passed from the caller.
 */

?>

<i class="fas fa-shopping-basket"></i> <?= $text ?>
