<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\ItemRepresentation $resource
 * @var \Omeka\Entity\User $user
 * @var int $selectionId
 * @var array $selections
 * @var array $records
 * @var bool $isGuestActive
 * @var bool $isSession
 */

// This template display a simple list of the current selection,
// unlike the full hierarchical list of selection-browse.

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$currentRecords = $records[$selectionId] ?? [];

$exporters = $records && $plugins->has('bulkExporters')
    ? $plugins->get('bulkExporters')()
    : [];
if ($exporters) {
    $ids = implode(',', array_keys($currentRecords));
    $route = 'site/resource/output';
    $this->headLink()
        ->appendStylesheet($this->assetUrl('css/bulk-export.css', 'BulkExport'));
}

$deleteText = $escapeAttr($translate('Remove from selection')); // @translate
?>

<details class="selection-list selection-details" <?= $siteSetting('selection_resource_show_open_list', true) ? 'open="open"' : '' ?>>
    <summary><h5><?= $translate('Selected resources') // @translate ?></h5></summary>

    <ul class="selection-resources" data-text-delete="<?= $deleteText ?>">
        <?php foreach ($currentRecords as $resourceId => $record): ?>
        <li data-id="<?= $resourceId ?>">
            <a href="<?= $record['url'] ?>"><?= $record['heading'] ?></a>
            <span class="selection-delete" data-id="<?= $resourceId ?>" data-url="<?= $record['url_remove'] ?>" title="<?= $deleteText ?>" aria-label="<?= $deleteText ?>"></span>
        </li>
        <?php endforeach; ?>
    </ul>

    <p class="selection-empty<?= count($currentRecords) ? '' : ' active' ?>"><?= $translate('No selection') // @translate ?></p>

    <?php if ($exporters): ?>
    <div class="bulk-export">
        <h5><?= $translate('Download selection') ?></h5>
        <ul class="formatters">
        <?php foreach ($exporters as $format => $label): ?>
            <?php $urlFormat = $url($route, ['resource-type' => 'resource', 'format' => $format], ['query' => ['id' => $ids]], true); ?>
            <li><a class="download-<?= $format ?>" href="<?= $escapeAttr($urlFormat) ?>"><?= $label ?></a></li>
        <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
</details>
