<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Omeka\Entity\User $user
 * @var int $selectionId
 * @var array $selections
 * @var array $records
 * @var bool $isGuestActive
 * @var bool $isSession
 * @var string $value
 * @var string $action
 * @var string $urlButton
 *
 * and options passed from the caller.
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$textSelect['unselected'] = $translate('Add to selection');
$textSelect['selected'] = $translate('Remove from selection');
$textSelect['add'] = $textSelect['unselected'];
$textSelect['delete'] = $textSelect['selected'];
$class = $value === 'selected' ? 'selected' : 'unselected';
$text = in_array($action, ['add', 'delete']) ? $textSelect[$action] : $textSelect[$class];
?>

<button class="selection-button selection-update <?= $class ?> selection-<?= $escapeAttr($action) ?>" data-id="<?= $resource->id() ?>" title="<?= $text ?>" data-action="<?= $escapeAttr($action) ?>" data-title-selected="<?= $textSelect['selected'] ?>" data-title-unselected="<?= $textSelect['unselected'] ?>" data-url="<?= $urlButton ?>">
    <span class="selection-icon"></span>
</button>
