<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $urlBrowse
 * @var bool $isGuestActive
 *
 * and options passed from the caller.
 * @var string`null $class
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');

$labelSelection = $siteSetting('selection_label', $translate('Selection'));
?>

<a class="selection browse <?= $class ?? '' ?>" href="<?= $urlBrowse ?>"><?= $escape($labelSelection) ?></a>
