<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\ItemRepresentation $resource
 * @var \Omeka\Entity\User $user
 * @var int $selectionId
 * @var array $selections
 * @var array $records
 * @var bool $isGuestActive
 * @var bool $isSession
 */

// For a better display, it is recommended to use the resource block or to edit
// the original item/show template of the theme, and any other one, to include
// the link to update the selection and to skip this partial. This partial can
// be skipped automatically with module BlocksDisposition.

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$selectionButton = $plugins->get('selectionButton');

$this->headLink()
    ->appendStylesheet($this->assetUrl('css/selection.css', 'Selection'));
$this->headScript()
    ->appendFile($this->assetUrl('js/selection.js', 'Selection'), 'text/javascript', ['defer' => 'defer']);

$medias = $resource->getControllerName() === 'item' ? $resource->media() : [];
?>

<details class="selection selection-details" <?= $siteSetting('selection_open', true) ? 'open="open"' : '' ?>>
    <summary><h4><?= $translate('Selection') ?></h4></summary>
    <?php if (count($medias)): ?>
    <h5><?= $translate('Item') ?></h5>
    <?php endif; ?>
    <div class="item resource">
        <?= $selectionButton($resource) ?>
        <?= $resource->linkPretty() ?>
    </div>
    <?php if (count($medias)): ?>
    <details class="media-list selection-details">
        <summary><h5><?= $translate('Media') ?></h5></summary>
        <?php foreach ($medias as $media): ?>
        <div class="media resource">
            <?= $selectionButton($media) ?>
            <?= $media->linkPretty() ?>
        </div>
        <?php endforeach; ?>
    </details>
    <?php endif; ?>

    <?php // The session selection list can be moved anywhere via the main layout. ?>
    <?= $this->partial('common/selection-list') ?>
</details>
