<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\ItemRepresentation $resource
 * @var \Omeka\Entity\User $user
 * @var int $selectionId
 * @var array $selections
 * @var array $records
 * @var bool $isGuestActive
 * @var bool $isSession
 */

// For a better display, it is recommended to use the resource block or to edit
// the original item/show template of the theme, and any other one, to include
// the link to update the selection and to skip this partial. This partial can
// be skipped automatically with module BlocksDisposition.

$plugins = $this->getHelperPluginManager();
$siteSetting = $plugins->get('siteSetting');

if (!$user && $siteSetting('selection_disable_anonymous')) return;

$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$selectionButton = $plugins->get('selectionButton');

$selectables = $siteSetting('selection_selectable_resources', ['items']);
$isMediaSelectable = in_array('media', $selectables);

$this->headLink()
    ->appendStylesheet($this->assetUrl('css/common-dialog.css', 'Common'))
    ->appendStylesheet($this->assetUrl('css/selection.css', 'Selection'));
$this->headScript()
    ->appendFile($this->assetUrl('js/common-dialog.js', 'Common'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($this->assetUrl('js/selection.js', 'Selection'), 'text/javascript', ['defer' => 'defer']);

$medias = $resource->getControllerName() === 'item' ? $resource->media() : [];

$openDetails = (bool) $siteSetting('selection_resource_show_open', true);

$labelSelection = $siteSetting('selection_label', $translate('Selection'));
?>

<details class="selection selection-details" <?= $openDetails ? 'open="open"' : '' ?>>
    <summary class="selection-summary" aria-expanded="<?= $openDetails ? 'true' : 'false' ?>"><?= $escape($labelSelection) ?></summary>
    <?php if ($isMediaSelectable && count($medias)): ?>
    <h5><?= $translate('Item') ?></h5>
    <?php endif; ?>
    <div class="item resource">
        <?= $selectionButton($resource) ?>
        <?= $resource->linkPretty() ?>
    </div>
    <?php if ($isMediaSelectable && count($medias)): ?>
    <details class="media-list selection-details">
        <summary class="selection-summary" aria-expanded="false"><?= $translate('Media') ?></summary>
        <?php foreach ($medias as $media): ?>
        <div class="media resource">
            <?= $selectionButton($media) ?>
            <?= $media->linkPretty() ?>
        </div>
        <?php endforeach; ?>
    </details>
    <?php endif; ?>
</details>
