<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Selection\Api\Representation\SelectionItemRepresentation|null $selectionItem
 * @var string $url
 * @var string $action deprecated "add" or "delete". Check selection item instead.
 * and options passed from the caller.
 */

$translate = $this->plugin('translate');

if (empty($selectionItem)):
    $text = $translate('Add to selection');
    $class = 'selection-add btn-primary';
else:
    $text = $translate('Remove from selection');
    $class = 'selection-delete btn-danger';
endif;
$this->vars()->offsetSet('text', $text);
?>

<button class="selection-update <?= $class ?>" title="<?= $text ?>" data-url="<?= $url ?>">
    <?= $this->partial('common/selection-button-content') ?>
</button>
