<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$siteSetting = $plugins->get('siteSetting');
?>

<ul>
    <li>
        <?= $hyperlink(
            $siteSetting('selection_label_guest_link') ?: $translate('My selection'), // @translate
            $url('site/guest/selection', ['action' => 'browse'], true)
        ) ?>
    </li>
</ul>
