<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemSetRepresentation $itemSet
 * @var \Omeka\Api\Representation\ItemRepresentation[] $items
 */

$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
$updateBasketLink = $this->plugin('updateBasketLink');

$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
if (isset($itemSet)):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
endif;
?>

<div id="content" role="main">
    <?php if (isset($itemSet)): ?>
        <?= $this->pageTitle($itemSet->displayTitle(), 2) ?>
        <h3><?= $translate('Item Set') ?></h3>
        <div class="metadata">
            <?= $itemSet->displayValues() ?>
        </div>
        <?= $this->pageTitle($translate('Items'), 3) ?>
    <?php else: ?>
        <?= $this->pageTitle($translate('Items'), 2) ?>
    <?php endif; ?>

    <?= $this->searchFilters() ?>

    <?= $hyperlink($translate('Advanced search'), $url(null, ['action' => 'search'], true), ['class' => 'advanced-search']) ?>

    <?= $pagination = $this->pagination() ?>

    <ul class="resource-list">
        <?php foreach ($items as $item): ?>
        <li class="item resource">
            <?= $item->linkPretty('medium') ?>
            <span><?= $updateBasketLink($item) ?></span>
            <?php if ($description = $item->displayDescription()): ?>
            <div class="description"><?= $description ?></div>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>

    <?= $pagination ?>

    <?php $this->trigger('view.browse.after'); ?>
</div>
