<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Selection\Api\Representation\SelectionRepresentation $selection
 * @var \Selection\Api\Representation\SelectionResourceRepresentation[] $selectionResources
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var array $resourcesByType
 * @var bool $isGuestActive
 * @var bool $allowIndividualSelect
 * @var string $disposition "list" or "hierarchy"
 */

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
?>

<div class="block block-selection">
    <?= $isGuestActive
        ? $partial("guest/site/guest/selection-resource-browse-$disposition")
        : $partial("selection/site/selection/selection-browse-$disposition") ?>
</div>
