<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau 2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Basket\Api\Representation\BasketItemRepresentation[] $basketItems
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$partial = $plugins->get('partial');
$updateBasketLink = $this->plugin('updateBasketLink');

$this->htmlElement('body')->appendAttribute('class', 'basket');
?>

<div id="content" role="main">
    <h2><?= $translate('Basket') ?></h2>

    <?php
    $resources = ['items' => [], 'media' => []];
    foreach ($basketItems as $basketItem):
        $resource = $basketItem->resource();
        $resources[$resource->resourceName()][] = $resource;
    endforeach;
    ?>

    <?php if (count($resources['items'])): ?>
        <h3><?= sprintf($translate('%d items'), count($resources['items'])) ?></h3>
        <div class="resource-list">
            <?php foreach ($resources['items'] as $item): ?>
                <?= $partial('basket/index/resource', ['resource' => $item]) ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php // TODO Create the layout for basket for media. ?>
    <?php if (count($resources['media'])): ?>
        <h3><?= sprintf($translate('%d media'), count($resources['media'])) ?></h3>
        <div class="resource-list">
            <?php foreach ($resource['media'] as $medium): ?>
                <?= $medium->render() ?>
                <?= $medium->displayValues() ?>
                <?= $updateBasketLink($medium) ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
