<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 */

$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$updateBasketLink = $this->plugin('updateBasketLink');

$this->htmlElement('body')->appendAttribute('class', 'item resource show');
?>

<div id="content" role="navigation">
    <?= $this->pageTitle($item->displayTitle(), 2) ?>
    <h3><?= $translate('Item') ?></h3>
    <?= $item->displayValues() ?>
    <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets)): ?>
        <h4><?= $translate('Item Sets') ?></h4>
        <?php /** @var \Omeka\Api\Representation\ItemSetRepresentation $itemSet */ ?>
        <?php foreach ($itemSets as $itemSet): ?>
        <div class="value">
            <?= $hyperlink($itemSet->displayTitle(), $itemSet->siteUrl()) ?>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
        <?php /** @var \Omeka\Api\Representation\MediaRepresentation $media */ ?>
    <?php $medias = $item->media(); ?>
    <?php if ($medias): ?>
    <div class="media-list">
        <?php foreach ($medias as $media): ?>
            <?= $media->linkPretty('medium', null, null, ['class' => 'media resource']) ?>
            <?= $updateBasketLink($media) ?>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <?php $this->trigger('view.show.after'); ?>
</div>
