<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */

$translate = $this->plugin('translate');
$text = $action === 'add' ? $translate('Add to basket') : $translate('Remove from basket');
$class = "basket-$action";
?>
<button class="basket-update <?php echo $class; ?>" title="<?php echo $text ;?>" data-url="<?php echo $url ?>">
    <?php
        echo $this->partial('basket/basket-button-content', [
            'action' => $action,
            'text' => $text,
        ]);
    ?>
</button>
