<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Omeka\Entity\User $user
 * @var int $selectionId
 * @var array $selections
 * @var array $records
 * @var bool $isGuestActive
 * @var bool $isSession
 */

echo $this->partial('common/selection-resource');
