<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var int $selectionId
 * @var array $selections
 * @var array $records
 * @var bool $isGuestActive
 * @var bool $isSession
 * @var bool $allowIndividualSelect
 */

// Browse the current selection, not all selections.

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$api = $plugins->get('api');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$thumbnail = $plugins->get('thumbnail');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$breadcrumbs = $plugins->has('breadcrumbs') ? $plugins->get('breadcrumbs') : null;
$bulkExport = $plugins->has('bulkExport') ? $plugins->get('bulkExport') : null;
$contactUs = $plugins->has('contactUs') ? $plugins->get('contactUs') : null;

// May be included in main layout.
$this->headLink()
    ->appendStylesheet($assetUrl('css/selection.css', 'Selection'));
$this->headScript()
    ->appendFile($assetUrl('js/selection.js', 'Selection'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'selection resource browse');

$currentSelection = $selections[$selectionId] ?? [];
$currentRecords = $records[$selectionId] ?? [];
$selectedRecords = $currentRecords;

$recordsByType = array_column($currentRecords, 'resource_name', 'id');
$countsByType = array_count_values($recordsByType) + ['items' => 0, 'media' => 0, 'item_sets' => 0, 'annotations' => 0];

$baseUrl = dirname($url('site/selection-id', ['id' => $selectionId, 'action' => '__'], true));
$deleteText = $escapeAttr($translate('Remove from selection')); // @translate
$selectText = $escapeAttr($translate('Select resource')); // @translate

// TODO Get the resources one time via api (currently only needed for thumbnail, not prepared early).
?>

<?php if ($breadcrumbs): ?>
<?= $breadcrumbs() ?>
<?php endif; ?>

<?= $this->pageTitle($selections[$selectionId]['label'] ?? $translate('Selection'), 2) ?>

<?php if ($isSession): ?>
<p>
    <strong><?= $translate('Warning') ?></strong>
    <?= $translate('This selection is stored in the session cookie. It will be lost if the cookie is cleared.') ?>
</p>
<?php endif; ?>

<div class="selection-list selections selection-flat">

    <?php if (count($currentRecords)): ?>
    <h3 class="selection-count"><?= sprintf($translate('%d resources'), count($currentRecords)) ?></h3>
    <?php else: ?>
    <p class="selection-empty">
        <?= $translate('The selection is empty.') // @translate ?>
    </p>
    <?php endif; ?>

    <?php $this->trigger('view.browse.before'); ?>
    <ul class="resource-list">
        <?php foreach ($selectedRecords as $resourceId => $record):
            $resource = $api->read($record['resource_name'], ['id' => $resourceId])->getContent();
            $resourceId = $record['id'];
            $resourceType = $record['type'];
            $heading = $record['heading'];
            $body = $record['body'];
            $linkContent = sprintf('%s<span class="resource-name">%s</span>', $thumbnail($resource, 'medium'), $escape($heading));
            ?>
        <li class="selection-resource resource <?= $resourceType ?>" data-id="<?= $resourceId ?>">
            <?php if ($allowIndividualSelect): ?>
            <input type="checkbox" name="resource_ids[]" class="selected-resource" value="<?= $resourceId ?>" aria-label="<?= $selectText ?>"/>
            <?php endif; ?>
            <?= $hyperlink->raw($linkContent, $record['url'], ['class' => 'resource-link']) ?>
            <?php if ($body): ?>
            <div class="description">
                <?= $escape($body) ?>
            </div>
            <?php endif; ?>
            <ul class="actions">
                <li><button type="button" class="selection-button selection-delete" data-id="<?= $record['id'] ?>" data-url="<?= $record['url_remove'] ?>"><?= $deleteText ?></button></li>
            </ul>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php $this->trigger('view.browse.after'); ?>

    <?php
    if ($currentRecords && $bulkExport) { // Does not support mixed types for now.
        echo '<h4>' . $translate('Select resources and download metadata') . '</h4>';
        $recordsByType = array_column($currentRecords, 'type', 'id');
        $countsByType = array_count_values($recordsByType);
        if (count($countsByType) === 1) {
            echo $bulkExport(array_keys($currentRecords), ['resourceType' => key($countsByType)]);
        } else {
            foreach (array_keys($countsByType) as $type) {
                echo $bulkExport(array_keys($currentRecords, $type), ['resourceType' => $type]);
            }
        }
    }
    ?>

    <?= $currentRecords && $contactUs ? $contactUs([
        'html' => '<h4>' . $translate('Select resources and send an email') . '</h4>',
    ]) : '' ?>

</div>
