<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var int $selectionId
 * @var array $selections
 * @var array $records
 * @var string $disposition
 * @var bool $isGuestActive
 * @var bool $isSession
 * @var bool $allowIndividualSelect
 */

// Template used by selection-browse.

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

// This is the base url, the query is added via js.
$siteSlug = $site->slug();
$baseUrl = dirname($url('site/selection-id', ['id' => $selectionId, 'action' => '__'], true));
$bulkExporters = $plugins->has('bulkExporters') ? $plugins->get('bulkExporters')() : null;
?>

<li class="selection-group group-level-__GROUP_LEVEL__" data-path="__GROUP_PATH__" data-level="__GROUP_LEVEL__">
    <div>
        <h4><span class="group-name">__GROUP_NAME__</span></h4>
        <details class="action-details">
            <summary class="selection-summary group-name" aria-expanded="false"><?= $translate('Actions') ?></summary>
            <ul class="actions">
                <?php if ($disposition === 'hierarchy'): ?>
                <li><button type="button" class="button add-group" data-url="<?= $baseUrl  ?>/add-group"><?= $escape($translate('Add a sub-selection')) ?></button></li>
                <?php endif; ?>
                <li><button type="button" class="button rename-group" data-url="<?= $baseUrl ?>/rename-group"><?= $escape($translate('Rename selection')) ?></button></li>
                <?php if ($disposition === 'hierarchy'): ?>
                <li><button type="button" class="button move-group" data-url="<?= $baseUrl ?>/move-group"><?= $escape($translate('Move selection')) ?></button></li>
                <?php endif; ?>
                <li><button type="button" class="button delete-group" data-url="<?= $baseUrl ?>/delete-group"><?= $escape($translate('Delete selection')) ?></button></li>
                <li><button type="button" class="button move-resource" data-url="<?= $baseUrl ?>/move"><?= $escape($translate('Move resources')) ?></button></li>
                <?php if ($bulkExporters):
                foreach ($bulkExporters as $format => $label):
                    $urlFormat = $url('site/resource/output', ['site-slug' => $siteSlug, 'controller' => 'resource', 'action' => 'browse', 'format' => $format]);
                ?>
                <li><a class="download-file download-id" href="<?= $urlFormat ?>" download="download" target="_self"><button type="button" class="export-group download-<?= $format ?>" data-url="<?= $urlFormat ?>"><?= $label ?></button></a></li>
                <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </details>
    </div>
    <ul class="resource-list selection-resources">
        __GROUP_RESOURCES__
    </ul>
</li>
