<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var int $selectionId
 * @var array $selections
 * @var array $records
 * @var string $disposition
 * @var bool $isGuestActive
 * @var bool $isSession
 * @var bool $allowIndividualSelect
 */

// Browse the current selection, not all selections.

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$api = $plugins->get('api');
$i18n = $plugins->get('i18n');
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$thumbnail = $plugins->get('thumbnail');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$partialLoop = $plugins->get('partialLoop');
$translatePlural = $plugins->get('translatePlural');
$guestNavigation = $user && $plugins->has('guestNavigation') ? $plugins->get('guestNavigation')() : null;
$breadcrumbs = $plugins->has('breadcrumbs') ? $plugins->get('breadcrumbs') : null;
$bulkExport = $plugins->has('bulkExport') ? $plugins->get('bulkExport') : null;
$contactUs = $plugins->has('contactUs') ? $plugins->get('contactUs') : null;

$hasGuestNav = $guestNavigation && $guestNavigation->getContainer()->count();

// May be included in main layout.
$this->headLink()
    ->appendStylesheet($assetUrl('css/selection.css', 'Selection'));
$this->headScript()
    ->appendFile($assetUrl('js/selection.js', 'Selection'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'selection resource browse');

$lang = $this->lang();
$filterLocale = (bool) $siteSetting('filter_locale_values');
$headingTerm = $siteSetting('browse_heading_property_term');
$bodyTerm = $siteSetting('browse_body_property_term');
$bulkExporters = $plugins->has('bulkExporters') ? $plugins->get('bulkExporters')() : null;

$currentSelection = $selections[$selectionId] ?? [];
$currentRecords = $records[$selectionId] ?? [];
$selectedRecords = $currentRecords;
$selection = $currentSelection;

$labelSelection = $siteSetting('selection_label', $translate('Selection'));

// All data needed to display each selected resource quickly via partialLoop.
$selectedRecordModel = [
    'site' => $site,
    'siteSlug' => $site->slug(),
    'selectionId' => $selectionId,
    'selection' => $selection,
    'record' => null,
    'disposition' => $disposition,
    'isGuestActive' => $isGuestActive,
    'isSession' => $isSession,
    'allowIndividualSelect' => $allowIndividualSelect,
    'url' => $url,
    'api' => $api,
    'i18n' => $i18n,
    'escape' => $escape,
    'translate' => $translate,
    'hyperlink' => $hyperlink,
    'thumbnail' => $thumbnail,
    'escapeAttr' => $escapeAttr,
    'headingTerm' => $headingTerm,
    'bodyTerm' => $bodyTerm,
    'defaultHeading' => ['default' => $translate('[Untitled]'), 'lang' => ($filterLocale ? [$lang, ''] : null)],
    'defaultBody' => ['lang' => ($filterLocale ? [$lang, ''] : null)],
    'defaultLang' => $filterLocale ? [$lang, ''] : null,
    'moveText' => $escapeAttr($translate('Move')),
    'deleteText' => $escapeAttr($translate('Remove from selection')),
    'selectText' => $escapeAttr($translate('Select resource')),
    'bulkExporters' => $bulkExporters,
];

$recordsByType = array_column($currentRecords, 'resource_name', 'id');
$countsByType = array_count_values($recordsByType) + ['items' => 0, 'media' => 0, 'item_sets' => 0, 'annotations' => 0];

// TODO Get the resources one time via api (currently only needed for thumbnail, not prepared early).
// $resources = $selectedRecords ? $api->search('items', ['id' => array_keys($selectedRecords)])->getContent() : [];
?>

<?php if ($breadcrumbs && !$hasGuestNav): ?>
<?= $breadcrumbs() ?>
<?php endif; ?>

<?php if ($hasGuestNav): ?>
<nav class="navigation-guest">
    <?= $guestNavigation->menu()->renderMenu() ?>
</nav>
<?php endif; ?>

<?= $this->pageTitle($selections[$selectionId]['label'] ?? $labelSelection, 2) ?>

<?php if ($isSession): ?>
<?php $labelWarning = $siteSetting('selection_warning_anonymous', $translate('This selection is stored in the session cookie. It will be lost if the cookie is cleared.')); ?>
<p class="selection-warning-anonymous">
    <strong><?= $translate('Warning') ?></strong>
    <?= $escape($labelWarning) ?>
</p>
<?php endif; ?>

<div class="selection-list selections selection-grouped">

    <?php if (count($currentRecords)): ?>
    <div class="selection-count">
        <?= sprintf($translatePlural('%s resource', '%s resources', count($currentRecords)), count($currentRecords)) ?>
    </div>
    <?php else: ?>
    <p class="selection-empty">
        <?= $translate('The selection is empty.') ?>
    </p>
    <?php endif; ?>

    <div class="selection-list-actions">
        <ul class="actions">
            <li>
                <button type="button" class="button add-group" data-msg-group-name="<?= $translate('Set selection name') ?>" data-url="<?= $url('site/selection-id', ['id' => $selectionId, 'action' => 'add-group'], true) ?>"><?= $translate('Create a selection') ?></button>
            </li>
        </ul>
    </div>

    <?php $this->trigger('view.browse.before'); ?>

    <?php // Groups and selected resources inside them. ?>
    <?php $templateGroup = $partial('selection/site/selection/selection-group'); ?>
    <ul class="resource-list selection-resources selection-structure selection-structure-flat" data-msg-add-group="<?= $translate('Set selection name') ?>" data-template-group="<?= $escapeAttr($templateGroup) ?>">
        <?php
        foreach ($selection['structure'] ?? [] as $groupFullPath => $group):
            // Prepare the partial loop.
            // WARNING: see js too.
            $selectedRecordModels = [];
            foreach ($group['resources'] ?? [] as $resourceId) {
                $record = $selectedRecords[$resourceId] ?? null;
                unset($selectedRecords[$resourceId]);
                if (!$record) continue;
                $selectedRecordModel['record'] = $record;
                $selectedRecordModels[] = $selectedRecordModel;
            }
            $replace = [
                '__GROUP_LEVEL__' => substr_count($groupFullPath, '/'),
                '__GROUP_PATH__' => $escapeAttr($groupFullPath),
                '__GROUP_NAME__' => '<span>' . strtr(ltrim($groupFullPath, '/'), ['/' => '</span><span>']) . '</span>',
                '__GROUP_RESOURCES__' => $selectedRecordModels
                    ? $partialLoop('selection/site/selection/selection-group-resource', $selectedRecordModels)
                    : '',
            ]; ?>
        <?= strtr($templateGroup, $replace) ?>
        <?php endforeach; ?>
    </ul>

    <?php // Remaining selected resources without group. ?>
    <?php if (count($selectedRecords)): ?>
    <ul class="resource-list selection-resources">
        <?php // Prepare the partial loop.
        $selectedRecordModels = [];
        foreach ($selectedRecords as $resourceId => $record) {
            $selectedRecordModel['record'] = $record;
            $selectedRecordModels[] = $selectedRecordModel;
        } ?>
        <?= $partialLoop('selection/site/selection/selection-group-resource', $selectedRecordModels) ?>
    </ul>
    <?php endif; ?>

    <?php $this->trigger('view.browse.after'); ?>

    <?php
    if ($currentRecords && $bulkExport) { // Does not support mixed types for now.
        echo '<h4>' . $translate('Select resources and download metadata') . '</h4>';
        $recordsByType = array_column($currentRecords, 'type', 'id');
        $countsByType = array_count_values($recordsByType);
        if (count($countsByType) === 1) {
            echo $bulkExport(array_keys($currentRecords), ['resourceType' => key($countsByType)]);
        } else {
            foreach (array_keys($countsByType) as $type) {
                echo $bulkExport(array_keys($currentRecords, $type), ['resourceType' => $type]);
            }
        }
    }
    ?>

    <?= $currentRecords && $contactUs ? $contactUs([
        'html' => '<h4>' . $translate('Select resources and send an email') . '</h4>',
    ]) : '' ?>

</div>

<?php // Common actions. ?>
<div id="selector-group" class="selector-group inactive" style="display:none;">
    <select name="group" aria-label="<?= $translate('Choose a selection') ?>">
        <option value="">/</option>
        <?php foreach ($selection ? array_keys($selection['structure']) : [] as $groupFullPath): ?>
        <option value="<?= $groupFullPath ?>"><?= strtr($groupFullPath, ['/' => ' / ']) ?></option>
        <?php endforeach ?>
    </select>
</div>
