<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var int $selectionId
 * @var array $selection
 * @var array $record
 *
 * // Helpers.
 * @var \Omeka\View\Helper\api $api
 * @var \Laminas\View\Helper\Url $url
 * @var \Omeka\View\Helper\I18n $i18n
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Omeka\View\Helper\Hyperlink $hyperlink
 * @var \Omeka\View\Helper\Thumbnail $thumbnail
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 *
 * // Static vars.
 * @var string $siteSlug
 * @var string $headingTerm
 * @var string $bodyTerm
 * @var array $defaultHeading
 * @var array $defaultBody
 * @var array $defaultLang
 * @var string $deleteText
 * @var string $moveText
 * @var array $bulkExporters
 */

// Partial loop template used by selection-browse.

if (!$record) return;

// This is the base url, the query is added via js.
$baseUrl = pathinfo($url('site/selection-id', ['id' => $selectionId, 'action' => '__'], true), PATHINFO_DIRNAME);
$resourceId = $record['id'];
$resourceType = $record['type'];
$resource = $api->read($record['resource_name'], $resourceId)->getContent();
$heading = $record['heading'];
$body = $record['body'];
$linkContent = sprintf('%s<span class="resource-name">%s</span>', $thumbnail($resource, 'medium'), $escape($heading));
?>

<li class="selection-resource resource <?= $resourceType ?>" data-id="<?= $resourceId ?>">
    <?= $hyperlink->raw($linkContent, $record['url'], ['class' => 'resource-link']) ?>
    <?php if ($body): ?>
    <div class="description">
        <?= $escape($body) ?>
    </div>
    <?php endif; ?>
    <details class="action-details">
        <summary class="group-name"><?= $translate('Actions') ?></summary>
        <ul class="actions">
            <?php if ($selection && $selection['structure']): ?>
            <li><button type="button" class="move-resource" data-url="<?= str_replace('/delete', '/move', $record['url_remove']) ?>"><?= $moveText ?></button></li>
            <?php endif; ?>
            <li><button type="button" class="selection-delete" data-url="<?= $record['url_remove'] ?>"><?= $deleteText ?></button></li>
        </ul>
    </details>
</li>
