<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var string $heading
 * @var string $body
 */
?>

<?= $resource->linkRaw($this->thumbnail($resource, 'medium')) ?>
<h4><?= $resource->link($heading) ?></h4>
<?php if ($body): ?>
<div class="description"><?= $body ?></div>
<?php endif; ?>
<?= $this->updateBasketLink($resource) ?>
