<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Selection\Api\Representation\SelectionRepresentation $selection
 * @var \Selection\Api\Representation\SelectionResourceRepresentation[] $selectionResources
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var array $resourcesByType
 */

// Template used by selection-resource-browse.

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

// This is the base url, the query is added via js.
$baseUrl = pathinfo($url('site/selection-id', ['id' => $selection ? $selection->id() : 0, 'action' => '__'], true), PATHINFO_DIRNAME);
?>

<li class="selection-group" data-path="__GROUP_PATH__">
    <div>
        <span class="group-name">__GROUP_NAME__</span>
        <ul class="actions">
            <li><button type="button" class="add-group" data-url="<?= $baseUrl  ?>/add-group"><?= $escape($translate('Add a sub-group')) ?></button></li>
            <li><button type="button" class="rename-group" data-url="<?= $baseUrl ?>/rename-group"><?= $escape($translate('Rename group')) ?></button></li>
            <li><button type="button" class="delete-group" data-url="<?= $baseUrl ?>/delete-group"><?= $escape($translate('Delete group')) ?></button></li>
            <li><button type="button" class="move-group" data-url="<?= $baseUrl ?>/move"><?= $escape($translate('Move resources')) ?></button></li>
        </ul>
    </div>
    <ul class="resource-list selection-resources">
        __GROUP_RESOURCES__
    </ul>
</li>
